Initial commit of Terraform deployment to automatically export ADX Assets to S3
aws-samples/aws-dataexchange-api-samples pull request #42
Opened 2021-01-29 10:20 UTC by gerrardcowburn

Initial commit of Terraform deployment to automatically export AWS Data Exchange Assets to S3 using Lambda and EventBridge

*Issue #, if available:*

*Description of changes:*
* Modified root level README.md to reference new contribution
* Added 'tf-auto-export-to-s3' folder under 'subscribers/python' folder

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-01-29 14:58 UTC, dblock requested changes
Awesome, thank you! 

I think we need to extract the Lambda code as source in this PR and have a way to "build" it. Maybe a `build.sh` that invokes `zip` will suffice?

2021-01-29 14:58 UTC, dblock commented on README.md
> +* [auto-export-to-s3](subscribers/python/tf-auto-export-to-s3): Terraform based deployment to automatically export newly published revisions to S3 using a CloudWatch Rule and Lambda
Let's put a period at the end of this sentence to feed my OCD ;)

2021-01-29 14:58 UTC, dblock commented on subscribers/python/tf-auto-export-to-s3/README.md
> +This sample shows how to set up an AWS Lambda function which will automatically export all newly published revisions for a given Data Set to S3. All infrastructure is setup using Terraform.
Data Set -> DataSet, and a few more places like this

2021-01-29 17:13 UTC, gerrardcowburn commented on README.md
> +* [auto-export-to-s3](subscribers/python/tf-auto-export-to-s3): Terraform based deployment to automatically export newly published revisions to S3 using a CloudWatch Rule and Lambda
Done :) Also added them to the bullets in the README.me in the sub folder

2021-01-29 17:14 UTC, gerrardcowburn commented on subscribers/python/tf-auto-export-to-s3/README.md
> +This sample shows how to set up an AWS Lambda function which will automatically export all newly published revisions for a given Data Set to S3. All infrastructure is setup using Terraform.
Done except the reference in the EventBridge Rule notification detail.

2021-02-01 14:59 UTC, merged

2021-02-01 14:59 UTC, dblock commented
Merged, thank you.