Adding sample code for exporting specific datasets
aws-samples/aws-dataexchange-api-samples pull request #48
Opened 2021-08-19 20:50 UTC by kwwaikar

*Issue #, if available:*
Adding sample code for exporting specific datasets
*Description of changes:*
Adding sample code for exporting specific datasets

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-08-19 22:34 UTC, melchii requested changes

2021-08-19 22:34 UTC, melchii commented on subscribers/python/download-datasets/export-dataset.py
> +#This function returns revision_ids corresponding to the dataset-id specified.
nit: Data Set is two words (applies everywhere)

2021-08-19 22:34 UTC, melchii commented on subscribers/python/download-datasets/export-dataset.py
> +        next_token = res.get('NextToken')
Simplify with do while statement?

2021-08-19 22:34 UTC, melchii commented on subscribers/python/download-datasets/export-dataset.py
> +    #print(revision_ids)
Remove?

2021-08-19 22:34 UTC, melchii commented on subscribers/python/download-datasets/export-dataset.py
> +    for rev in revisions:
rev -> revision

2021-08-20 17:26 UTC, kwwaikar commented on subscribers/python/download-datasets/README.md
> +# Download all Entitled Assets (Python)
Renamed to Export entitled data set assets

2021-08-20 17:26 UTC, kwwaikar commented on subscribers/python/download-datasets/README.md
> +This example accepts dataset_id(s),bucket,region, and exports all revisions corresponding to dataset-ids specified into an S3 bucket.
fixed

2021-08-20 17:28 UTC, kwwaikar commented on subscribers/python/download-datasets/README.md
> +* AmazonS3FullAccess
Changed DataExchangeFullAccess to DataExchangeSubscriberFullAccess. Yes, subscriber full access policy does not include S3 permissions

2021-08-20 17:28 UTC, kwwaikar commented on subscribers/python/download-datasets/README.md
> +* AWSDataExchangeFullAccess
Fixed.

2021-08-20 17:28 UTC, kwwaikar commented on subscribers/python/download-datasets/export-dataset.py
> +#This function returns revision_ids corresponding to the dataset-id specified.
Fixed.

2021-08-20 17:29 UTC, kwwaikar commented on subscribers/python/download-datasets/export-dataset.py
> +        next_token = res.get('NextToken')
Skipped due to lack of native support for do-while in python.

2021-08-20 17:29 UTC, kwwaikar commented on subscribers/python/download-datasets/export-dataset.py
> +    #print(revision_ids)
fixed.

2021-08-20 17:29 UTC, kwwaikar commented on subscribers/python/download-datasets/export-dataset.py
> +    for rev in revisions:
Fixed.

2021-08-20 17:57 UTC, melchii commented on subscribers/python/export-data-sets/export-data-sets.py
> +                    break
This will complete successfully if all jobs fail. Is that desired?

2021-08-20 18:12 UTC, merged